export type Article = {
  slug: string;
  n: number;
  titleUz: string;
  titleRu: string;
  leadUz: string;
  leadRu: string;
  bodyUz: string[];
  bodyRu: string[];
};

export const ARTICLES: Article[] = [
  {
    slug: 'page-1',
    n: 1,
    titleUz: 'Nima uchun biznesingiz Google’da bo‘lishi shart?',
    titleRu: 'Почему вашему бизнесу обязательно быть в Google?',
    leadUz: 'Mijoz xariddan oldin so‘raydi, tekshiradi, solishtiradi va Google‘ga kiradi. Agar siz u yerda yo‘q bo‘lsangiz — mijoz raqibingizga ketadi.',
    leadRu: 'Перед покупкой клиент спрашивает, проверяет, сравнивает и идёт в Google. Если вас там нет — клиент уходит к конкуренту.',
    bodyUz: [
      'Faraz qiling, sizga nimadir juda zarur, ya’ni sotib olishni istayapsiz. Masalan, Tesla yoki noutbukning so‘nggi modeli. Inson xariddan oldin nima qiladi?',
      'Avval do‘stlaringizdan, hamkasblaringizdan yoki bu sohani yaxshi tushunadigan tanish ekspertlardan so‘raysiz. Ular sizga aniq va lo‘nda javob beradi: «Men shuni olganman, zo‘r. Mana bu yerga borasan va o‘sha yerdan olasan.» Yoki ChatGPT ni ochasiz, yaxshilab so‘rab olasiz. U sizga barcha variantlarni tahlil qilib, solishtirib, eng yaxshisini tavsiya qiladi.',
      'Lekin yakuniy qarorni qayerda berasiz? Baribir Google‘da. O‘sha mahsulotni qidirasiz, «otzyv»larni o‘qiysiz, narxlarni va kompaniyani solishtirasiz va shundan keyingina qaror qabul qilasiz.',
      'Bu zamonda odamlar shunday «dasturlanib» bo‘lishgan. Boshqa yo‘li deyarli yo‘q. Chunki sotib olishdan oldingi eng oxirgi ko‘prik — bu Google‘ga murojaat qilishdir.',
      'Mana muhim nuqta: insоn xaridga tayyor bo‘lganda Google‘ga kiradi. U yerga kirgan odam — allaqachon issiq mijoz. Unga faqat bitta narsa kerak — ishonch. Agar siz Google‘da yo‘q bo‘lsangiz, mijozingiz raqibingiznikiga ketadi. Oddiy.',
      'Bugun odamlar shunday fikrlaydi: izlash → tekshirish → ishonch → xarid. Va bu jarayonda Google eng oxirgi va eng muhim ko‘prik. Savol: nega biznesingiz aynan shu joyda ko‘rinmasligi kerak? Nega mijoz sizni emas, boshqani topishi kerak? Google‘da ko‘rinayotganlar jimgina ishlayapti — shovqinsiz, lekin natija bilan.',
    ],
    bodyRu: [
      'Представьте, вам что-то нужно купить — например, Tesla или последнюю модель ноутбука. Что человек делает перед покупкой?',
      'Сначала спрашивает у друзей, коллег или знакомых экспертов. Они дают конкретный совет: «Я брал такой, отличный, иди туда — там и купишь». Или открываете ChatGPT, спрашиваете, и он сравнивает варианты, рекомендует лучший.',
      'Но финальное решение принимаете где? Всё равно в Google. Ищете тот же товар, читаете отзывы, сравниваете цены и компании — и только потом принимаете решение.',
      'В наше время люди именно так «запрограммированы». По-другому почти никак. Потому что последний мост перед покупкой — это обращение к Google.',
      'Главная мысль: когда человек готов купить — он идёт в Google. Тот, кто там — горячий клиент. Ему нужно одно: доверие. Если вас в Google нет — клиент уходит к конкуренту. Просто.',
      'Современный путь покупателя: поиск → проверка → доверие → покупка. И в этой цепочке Google — последний и самый важный мост. Вопрос: почему вашего бизнеса там не должно быть? Те, кто виден в Google, работают тихо — без шума, но с результатом.',
    ],
  },
  {
    slug: 'page-2',
    n: 2,
    titleUz: 'Google Ads reklamasi qaysi auditoriyaga chiqadi?',
    titleRu: 'На какую аудиторию выходит реклама Google Ads?',
    leadUz: 'Google sizning mijozingizni siz bilganingizdan ko‘ra ko‘proq biladi. Lekin agar auditoriyani noto‘g‘ri sozlasangiz, reklama puli osmonga uchadi.',
    leadRu: 'Google знает вашего клиента лучше, чем вы. Но если неправильно настроить аудиторию — рекламный бюджет улетит «в небо».',
    bodyUz: [
      'Google sizni ham, mijozlaringizni ham juda yaxshi biladi: nimani izlashayotgani, qaysi saytlarga kirishayotgani, internetda qancha pul sarflashayotgani, nimani sotib olishayotgani, qaysi shaharlarga borishayotgani, hatto xatlarda qaysi kalit so‘zlardan foydalanishayotganini.',
      'Google sizdan kim sotib olishi mumkinligini aniq biladi va reklamangizni aynan o‘shalarga ko‘rsatadi. Lekin agar ilm bilan ishlamasangiz — reklamangizni arzon auditoriya bosadi, pullaringiz esa osmonga uchib ketadi.',
      'Misol uchun, 10 ta odamga reklama yetib bormoqda. Ularning taxminiy taqsimoti: 10% — yirik korxonaning TOP-menejeri, unga zudlik bilan katta hajmda mahsulot kerak. 10% — kichik va o‘rta biznes egasi, hozir shartnoma imzolashga tayyor. 20% — salohiyatli mijozlar, qancha tez bo‘lsa shuncha pul to‘lashga tayyor. 20% — umuman sotib olmaydigan, shunchaki ma’lumot izlovchilar. 40% — keyinchalik sotib olish niyatida narxlarni kuzatayotgan mijozlar.',
      'Eng muhimi: Google birinchi bo‘lib reklamangizni eng pastdagi 2 toifaga ko‘rsatadi. Bu holat 95% reklama sozlovchilarda kuzatiladi. Demak, har qanday biznesda reklamani bosadigan turli toifalar mavjud va to‘g‘ri targeting strategiyasi — biznesning muvaffaqiyatiga kalit rol o‘ynaydi.',
    ],
    bodyRu: [
      'Google знает и вас, и ваших клиентов очень хорошо: что они ищут, какие сайты посещают, сколько тратят в интернете, что покупают, в какие города ездят, даже какие ключевые слова используют в письмах.',
      'Google точно знает, кто может у вас купить, и показывает рекламу именно им. Но если работать не по науке — рекламу будет кликать дешёвая аудитория, а деньги — улетать в небо.',
      'Пример: 10 человек видят рекламу. Их типичный состав: 10% — TOP-менеджер крупной корпорации, нужен срочно большой объём; 10% — владелец малого/среднего бизнеса, готов подписать контракт сейчас; 20% — потенциальные клиенты, готовы платить за скорость; 20% — вообще не покупают, просто ищут информацию; 40% — планируют купить позже, мониторят цены.',
      'Главное: Google по умолчанию показывает рекламу сначала двум нижним категориям. Это происходит у 95% настроек. То есть в любой нише есть разные сегменты — и правильная стратегия таргетинга играет ключевую роль в успехе бизнеса.',
    ],
  },
  {
    slug: 'page-3',
    n: 3,
    titleUz: 'Saytni Google TOP-10 ga qanday olib chiqish: 2026 uchun strategiya',
    titleRu: 'Как поднять сайт в TOP-10 Google: стратегия на 2026',
    leadUz: 'Saytni TOP‘ga chiqarish — bu omad emas, balki tartib. To‘g‘ri ketma-ketlikda 7 ta ishni qilsangiz, natija keladi.',
    leadRu: 'Поднять сайт в TOP — это не удача, а порядок. Если выполнить 7 шагов в правильной последовательности — результат придёт.',
    bodyUz: [
      'O‘zbekiston digital bozori bo‘sh bo‘lgani uchun qozoqlar, ruslar, belaruslar va boshqalar kirib kelyapti. O‘z bizneslari bilan Google va Yandex top o‘rinlarini egallamoqda. Yaxshi joylarni ilib ketishadi — harakat qilib qoling.',
      'Saytni SEO orqali topga chiqarish uchun 7 ta ishni amalga oshirish kerak:',
      '✔️ Kalit so‘zlarni to‘g‘ri tanlash. Bu fundament — noto‘g‘ri so‘zlardan natija yo‘q.',
      '✔️ Shu so‘zlar atrofida «semantik yadro» yaratish. Bu — saytning butun strukturasiga aks etadi.',
      '✔️ Original, foydali matn tayyorlash. Plagiat bilan TOP‘ga chiqib bo‘lmaydi.',
      '✔️ Saytni texnik optimallashtirish (tezlik, mobile, struktura).',
      '✔️ Foydalanuvchi tajribasi va konversiyani yaxshilash.',
      '✔️ Tashqi saytlardan tabiiy havolalar (backlinks) yig‘ish.',
      '✔️ Saytni Google Search Console‘ga ulash va indekslash.',
      'Eng muhim: faqat shu ishlarni to‘g‘ri va aql bilan qilsangizgina natija bo‘ladi. SEO ni bilmasangiz, kontekst-reklamaga «otning kallasidek» pul to‘lab yuraverasiz, va konkurentlar bosib tashlasa — byudjet osmonga uchib ketadi, natijasiz qolasiz.',
    ],
    bodyRu: [
      'Узбекский digital-рынок пока пустоват, и сюда заходят казахи, русские, белорусы и другие. Со своими бизнесами они занимают топ Google и Yandex. Хорошие места разберут — действуйте.',
      'Чтобы поднять сайт в TOP через SEO, нужно сделать 7 шагов:',
      '✔️ Правильно подобрать ключевые слова. Это фундамент — без них результата не будет.',
      '✔️ Построить «семантическое ядро» вокруг этих ключей. Оно определяет всю структуру сайта.',
      '✔️ Подготовить оригинальный полезный контент. С плагиатом в TOP не выйдешь.',
      '✔️ Технически оптимизировать сайт (скорость, mobile, структура).',
      '✔️ Улучшить UX и конверсию.',
      '✔️ Собрать естественные внешние ссылки (бэклинки).',
      '✔️ Подключить сайт к Google Search Console и обеспечить индексацию.',
      'Главное: результат будет только если делать всё правильно и осознанно. Без SEO будете тратить «кучу денег» на контекст, и когда конкуренты вас «задавят» — бюджет улетит, а результата не будет.',
    ],
  },
  {
    slug: 'page-4',
    n: 4,
    titleUz: 'Google — bepul mijozlar oqimi: biznes uchun eng kuchli manba',
    titleRu: 'Google — бесплатный источник клиентов для бизнеса',
    leadUz: 'Google — bu faqat reklama platformasi emas. Birinchi navbatda u qidiruv tizimi. Demak, qidiruv bor ekan — bepul, organik mijozlar ham bor.',
    leadRu: 'Google — это не только реклама. В первую очередь это поисковая система. А раз есть поиск — есть и бесплатные органические клиенты.',
    bodyUz: [
      'Ko‘pchilik kontekst reklama uchun pul to‘lab 3-4 ta o‘ringa talashadi, lekin SEO haqida ham qayg‘urishni unutib qo‘yadi. Bu — katta xato.',
      'Agar saytingiz Google top-10 da joylashib olsa — o‘sha sohaning kamida uchdan bir mijozlari sizniki bo‘ladi. Tasavvur qiling: shu masshtabni, shu pul oqimini.',
      'Bizning saytimiz «SEO xizmati» deb qidirilganda Google‘da 1-o‘rinda chiqyapti — hech qanday Google Ads‘siz, faqat organik (toza) SEO orqali. «Naming xizmati» deb qidirilganda esa bizning mijozimiz sayti 1-o‘rinni egallab turibdi. Bunday misollar bizda ko‘p.',
      'SEO qanday ishlaydi? Google saytingizdagi matnni o‘qiydi va baholaydi: foydalimi yoki yo‘q, odamlar saytda qolayaptimi yoki chiqib ketyaptimi. Google foydali manbani yaxshi ko‘radi va reytingda tepaga ko‘taradi.',
      'Shu sababli saytingizda foydali va original ma‘lumotlar bo‘lishi shart. 2-3 ta yo‘nalishli sahifa, to‘g‘ri kalit so‘zlar va foydali kontent — bu mavjud strategiya. Bizning natijalarimiz reklamasiz, faqat organik SEO orqali olingan.',
    ],
    bodyRu: [
      'Многие платят за контекст, чтобы занять 3-4 платных места, но забывают про SEO. Это — большая ошибка.',
      'Если сайт займёт места в Google TOP-10, минимум треть клиентов вашей ниши — ваши. Представьте масштаб и денежный поток.',
      'Наш сайт по запросу «SEO xizmati» стоит в Google на 1-м месте — без Google Ads, только органический SEO. По «naming xizmati» сайт нашего клиента занимает 1-е место. Таких примеров у нас много.',
      'Как работает SEO? Google читает и оценивает контент сайта: полезен или нет, остаются ли люди на сайте или уходят. Google любит полезные источники и поднимает их в рейтинге.',
      'Поэтому на сайте должен быть полезный и оригинальный контент. 2-3 тематические страницы, правильные ключи, полезный контент — это рабочая стратегия. Все наши результаты получены без рекламы, только через органический SEO.',
    ],
  },
  {
    slug: 'page-5',
    n: 5,
    titleUz: 'Google Ads reklamasini qachon yoqish kerak?',
    titleRu: 'Когда запускать рекламу Google Ads?',
    leadUz: 'Google Ads ni shunchaki yoqib qo‘yish yetarli emas. Uni to‘g‘ri vaqtda, to‘g‘ri auditoriyaga ko‘rsatish — bu sotuv va klik orasidagi farq.',
    leadRu: 'Просто включить Google Ads — недостаточно. Показывать в правильное время правильной аудитории — это разница между кликом и продажей.',
    bodyUz: [
      'Ko‘pchilik Google Ads reklamasini yoqib, 24/7 ishlatib qo‘yadi va oy oxirida umumiy natijaga qaraydi. Bu — katta xato. Pul ketadi, lekin qo‘ng‘iroq yo‘q.',
      'Google Ads‘da 3 xil vaqt bor: faol vaqt (oltin soatlar) — qo‘ng‘iroq va sotuv tez keladi; o‘rtacha vaqt — murojaat bor, lekin hammasi sotuvga aylanmaydi; passiv vaqt — bosishlar bor, lekin qo‘ng‘iroq yo‘q. Aynan passiv vaqtda byudjetning katta qismi bekorga ketadi.',
      'B2B va B2C farqi: B2B (ERP, CRM, ulgurji, ishlab chiqarish, SEO/marketing) — ish kuni, soat 09:00–18:00. Tushlikda va ish vaqtidan tashqari faollik tushadi. B2C (klinikalar, kurslar, maishiy xizmatlar) — kechqurun va dam olish kunlari yaxshi ishlaydi, chunki odamlar ish vaqtida band.',
      'To‘g‘ri vaqtni tanlash beradi: bekor kliklar kamayadi, reklama narxi pasayadi, real mijozlar soni oshadi. Eng muhimi — bir xil byudjet bilan ko‘proq sotuv qilasiz.',
      'Mijozlaringiz qachon qaror qabul qilishini bilsangiz — reklama byudjeti sotuvga ishlaydi. Bilmasangiz — bekorga ketadi.',
    ],
    bodyRu: [
      'Многие включают Google Ads и крутят 24/7, в конце месяца смотрят на общий результат. Это большая ошибка. Деньги уходят — звонков нет.',
      'В Google Ads есть 3 режима времени: активное (золотые часы) — звонки и продажи идут; среднее — обращения есть, но не все конвертятся; пассивное — клики есть, но звонков почти нет. Именно в пассивное время и сжигается большая часть бюджета.',
      'B2B vs B2C: B2B (ERP, CRM, опт, производство, SEO/маркетинг) — рабочий день, 09:00–18:00. В обед и после работы активность падает. B2C (клиники, курсы, бытовые услуги) — вечером и в выходные, так как люди днём заняты на работе.',
      'Правильный выбор времени даёт: меньше пустых кликов, ниже цена рекламы, больше реальных клиентов. Главное — при том же бюджете больше продаж.',
      'Если знаете, когда ваши клиенты принимают решение, реклама работает на продажу. Если не знаете — бюджет уходит впустую.',
    ],
  },
  {
    slug: 'page-6',
    n: 6,
    titleUz: 'Reklamaning eng muhim joyi — bu sizning sayt',
    titleRu: 'Самое важное в рекламе — это ваш сайт',
    leadUz: 'Reklama faqat odamni saytga olib keladi. Qolgan ishni esa saytning o‘zi qiladi.',
    leadRu: 'Реклама лишь приводит человека на сайт. Остальное делает сам сайт.',
    bodyUz: [
      'Ko‘pchilik Google Ads ni sozlashda kalit so‘zga, e’lon matniga, dizaynerlik bannerlarga, byudjetga e’tibor qaratadi. Aslida esa reklamaning eng muhim joyi — sizning sayt.',
      'Reklama foydali ishlaydi faqat shunda agar sayt tushunarli, tez, ishonchli va aniq taklifli bo‘lsa. Aks holda eng zo‘r reklama ham foyda bermaydi — pul yonadi, mijoz yo‘q.',
      'Yomon sayt — bu reklamaning eng katta dushmani. Klik bo‘ladi, lekin foydalanuvchi tushunmaydi, ishonmaydi, qaror qilmaydi — chiqib ketadi.',
      'Shu sababli ishni reklamadan emas, saytdan boshlang. Avval saytni sotuvga moslang: tushunarli qiling, ishonch beradigan holga keltiring, aniq taklif qo‘ying. Shundan keyin reklama yoqing. Shunda hatto arzimas byudjet ham ishlaydi.',
    ],
    bodyRu: [
      'Многие при настройке Google Ads сосредоточены на ключах, тексте объявлений, дизайне баннеров, бюджете. На самом деле самое важное в рекламе — это ваш сайт.',
      'Реклама работает только если сайт понятный, быстрый, вызывает доверие и имеет чёткий оффер. Иначе самая сильная реклама не даст эффекта — деньги сгорают, клиентов нет.',
      'Плохой сайт — главный враг рекламы. Клик есть, но пользователь не понимает, не доверяет, не принимает решение — уходит.',
      'Поэтому начинайте не с рекламы, а с сайта. Сначала подготовьте сайт к продажам: сделайте понятным, вызывающим доверие, добавьте чёткий оффер. Только после этого включайте рекламу. Тогда даже скромный бюджет начнёт работать.',
    ],
  },
  {
    slug: 'page-7',
    n: 7,
    titleUz: 'Google va SEO‘da 1-o‘rin afsonasi',
    titleRu: 'Миф о 1-м месте в Google и SEO',
    leadUz: '«Agar 1-o‘rinda chiqsam — hamma mijoz menga keladi.» Bu mashhur fikr, lekin u — afsona. Top ≠ sotuv.',
    leadRu: '«Если буду на 1-м месте — все клиенты ко мне». Это популярное убеждение — но миф. Топ ≠ продажа.',
    bodyUz: [
      'Bugungi Google foydalanuvchisi avvalgidek sodda emas. U shunchaki birinchi chiqib turgan saytni ochib darrov qaror qabul qilmaydi.',
      'Qidiruv qilgan odam: birinchi natijani ochadi, keyin ikkinchi va uchinchini ko‘radi, solishtiradi va shundan keyingina qaror qiladi. Ya‘ni 1-o‘rin — yakuniy qaror emas, balki boshlang‘ich nuqta.',
      'Agar siz 1-o‘rinda bo‘lsangiz-u, lekin taklifingiz noaniq, sayt ishonch uyg‘otmasa, matnlar tushunarsiz bo‘lsa — mijoz sizni emas, pastroqda turgan raqobatchingizni tanlaydi.',
      'Foydalanuvchi reytingidan ko‘ra ko‘proq quyidagilarga qaraydi: sarlavha qanchalik aniq; taklif foydaliroqmi; sayt tez ochiladimi; dizayn ishonch beradimi; real muammo yechimi bormi.',
      'SEO‘da yutadiganlar — eng baland turganlar emas, balki eng tushunarli, ishonchli va foydali bo‘lganlar. Maqsad — reyting emas, foydalanuvchini qoniqtirish. Hatto 1-o‘rinda bo‘lsangiz ham, agar sayt foydali bo‘lmasa, odamlar uzoq qolmaydi va Google sizni vaqt o‘tib baribir pastga tushiradi.',
      'Aslida nimaga intilish kerak? Savolni boshqacha qo‘ying: «Qanday qilib mijoz tanlaydigan sayt bo‘laman?» — emas «Qanday qilib 1-o‘ringa chiqaman?» Foydalanuvchi haqida o‘ylasangiz, muammoni hal qilsangiz va aniq taklif bersangiz — Google reytingi ham, mijozlar ham o‘z-o‘zidan keladi.',
    ],
    bodyRu: [
      'Сегодняшний пользователь Google не такой простой как раньше. Он не открывает первый сайт и сразу не принимает решение.',
      'Поисковый путь: открывает первый результат, потом смотрит второй и третий, сравнивает — и только потом решает. То есть 1-е место — не конец, а начало.',
      'Если вы на 1-м месте, но оффер расплывчат, сайт не вызывает доверия, тексты непонятны — клиент выберет конкурента ниже.',
      'Пользователь смотрит не на рейтинг, а на: насколько ясен заголовок; в чём польза предложения; быстро ли открывается сайт; вызывает ли дизайн доверие; решает ли сайт реальную проблему.',
      'В SEO выигрывают не самые высокие, а самые понятные, надёжные и полезные. Цель — не рейтинг, а удовлетворение пользователя. Даже на 1-м месте, если сайт бесполезен, люди не задерживаются, и Google со временем опустит вас вниз.',
      'К чему стремиться? Перефразируйте вопрос: не «как попасть на 1-е место», а «как стать сайтом, который клиент выбирает». Думайте о пользователе, решайте его проблему, давайте чёткий оффер — и рейтинг, и клиенты придут сами.',
    ],
  },
  {
    slug: 'page-8',
    n: 8,
    titleUz: 'Google‘da nega faqat 4 ta pullik o‘rin bor va hamma yuta olmaydi',
    titleRu: 'Почему в Google всего 4 платных места и почему выигрывают не все',
    leadUz: 'Google qidiruvining eng yuqorisida atigi 4 ta pullik o‘rin bor. Bu yerda yutish faqat pul masalasi emas — bu tizim, tajriba va doimiy kurash.',
    leadRu: 'В верху выдачи Google всего 4 платных места. Победа здесь — не просто бюджет. Это система, опыт и постоянная борьба.',
    bodyUz: [
      'Google qidiruv natijalarining eng yuqorisida joylashgan 4 ta o‘rin — bu pullik joylar. Bu o‘rinlarda chiqish uchun reklama byudjeti sarflanadi. Pul to‘lanmasa — e’lon ko‘rsatilmaydi. Ularning ostidan tabiiy (organik) natijalar boshlanadi.',
      'Masalan, «xususiy klinika Toshkentda» deb qidirilsa, shu sohada reklama qilayotganlar 15-20 ta, ba’zan 50-100 taga yetadi. Va ularning barchasi shu 4 ta o‘rin uchun kurashadi.',
      'Google kimni chiqaradi? U reklama beruvchilarni solishtiradi va baholaydi: sozlamalari, reklama sifati, foydalanuvchiga qiziqarliligi, byudjeti bo‘yicha. Agar reklama sifatsiz yoki byudjet tugasa — u ko‘rsatilmaydi, o‘rnini boshqasi egallaydi. Bu jarayon doimiy.',
      'Nega hamma yuta olmaydi? Chunki ko‘pchilik faqat pulga tayanadi, strategiya haqida o‘ylamaydi, reklama va sayt uyg‘unligini hisobga olmaydi, foydalanuvchi tajribasini e’tiborsiz qoldiradi. Natijada klik bo‘ladi, lekin mijoz bo‘lmaydi.',
      'Google‘da chiqish — bu omad emas. Bu hisob-kitob, tajriba va tizim. Agar tizim to‘g‘ri qurilmasa — pul ketadi, natija yo‘q. Yutish uchun kerak: to‘g‘ri strategiya, sifatli sozlash, foydalanuvchini tushunish.',
    ],
    bodyRu: [
      'В верху выдачи Google размещаются 4 платных места. Чтобы туда попасть, нужен рекламный бюджет. Не платишь — не показываешься. Под этими 4 местами начинаются органические результаты.',
      'Например, по запросу «частная клиника Ташкент» рекламируется 15-20 компаний, иногда 50-100. И все они борются за эти же 4 места.',
      'Кого Google выбирает? Он сравнивает рекламодателей: настройки, качество объявления, релевантность пользователю, бюджет. Если качество низкое или бюджет закончился — реклама не показывается, её место занимает следующий. Процесс непрерывный.',
      'Почему не все выигрывают? Многие полагаются только на бюджет, не думают о стратегии, не учитывают связку «реклама — сайт», игнорируют UX. В итоге клики есть, а клиентов нет.',
      'Попасть в Google — не удача. Это расчёт, опыт и система. Если система выстроена неправильно — деньги уходят, результата нет. Для победы нужны: правильная стратегия, качественная настройка, понимание пользователя.',
    ],
  },
  {
    slug: 'page-9',
    n: 9,
    titleUz: 'Google statistikasi: raqamlar nima deydi va biznes uchun nimani anglatadi',
    titleRu: 'Статистика Google: что говорят цифры и что это значит для бизнеса',
    leadUz: 'Google — kuniga 3 milliard odam kiradi. Statistika bilish yetarli emas — undan to‘g‘ri xulosa chiqarish muhim.',
    leadRu: 'В Google ежедневно заходят 3 миллиарда человек. Знать статистику мало — важно сделать правильные выводы.',
    bodyUz: [
      '1) Google — dunyodagi eng katta oqim. Kuniga 3 milliarddan ortiq odam kiradi. Agar siz Google‘da yo‘q bo‘lsangiz — mijoz sizni ko‘rmaydi.',
      '2) Foydalanuvchi Google‘da uzoq qoladi. O‘rtacha har bir odam kuniga 10 daqiqa Google qidiruviga sarflaydi va 8 ta sahifani ko‘radi. «Bor bo‘lish» yetarli emas — to‘g‘ri ko‘rinish kerak.',
      '3) 1-o‘rin hammani yutib ketadi. Google‘ning 1-o‘rnida chiqqan sayt barcha kliklarning 28% ini oladi. Yuqori o‘rin — katta imkoniyat, lekin u joyga chiqish strategiya va sifat talab qiladi.',
      '4) Pastga tushgan sari trafik kamayadi. 2-o‘rin — 14% klik, 3-o‘rin — 8% klik. Har bir pastga tushish — ikki baravar kam trafik degani.',
      '5) Odamlar ko‘proq organik natijani bosadi. Atigi 1,5-2% kontekst reklamani bosadi, 33% esa tabiiy (organik) natijalarni tanlaydi. Organik trafik arzonroq va ishonchliroq.',
      '6) Ko‘pchilik umuman bosmaydi. 64% odam nimanidir qidiradi va hech narsani bosmasdan chiqib ketadi. Sarlavha qiziqtirmagan yoki tavsif ishonch bermagan bo‘lishi mumkin.',
      '7) Ikkinchi sahifa deyarli ishlamaydi. Qidiruv qilganlarning atigi 9% i top-10 natijalarni ko‘rib bo‘lgach, ikkinchi sahifaga o‘tadi. Eng katta maqsad: birinchi sahifada bo‘lish.',
      'Xulosa: SEO‘ga e‘tibor bermasangiz va faqat reklama bilan cheklansangiz, Google‘dagi eng katta imkoniyatni boy beryapsiz. Statistikani bilish yetarli emas — undan to‘g‘ri xulosa chiqarish muhim.',
    ],
    bodyRu: [
      '1) Google — самый большой поток в мире. Более 3 миллиардов человек заходят ежедневно. Нет в Google — клиент вас не видит.',
      '2) Пользователь проводит в Google много времени. В среднем 10 минут в день и 8 страниц. Просто «быть» — мало, нужно правильно показываться.',
      '3) 1-е место забирает большинство. Сайт на 1-м месте получает 28% всех кликов. Высокое место — большая возможность, но туда нужны стратегия и качество.',
      '4) С каждой позицией ниже — трафика вдвое меньше. 2-е место — 14% кликов, 3-е — 8%. Каждый шаг вниз — вдвое меньше потока.',
      '5) Люди чаще кликают по органике. Только 1,5-2% кликают на контекстную рекламу, а 33% выбирают органические результаты. Органика дешевле и вызывает больше доверия.',
      '6) Многие вообще не кликают. 64% людей ищут что-то и уходят, ничего не кликнув. Заголовок не зацепил или описание не вызывает доверия.',
      '7) Вторая страница почти не работает. Только 9% доходят до 2-й страницы. Главная цель: быть на первой странице.',
      'Вывод: если игнорировать SEO и опираться только на рекламу, вы упускаете главную возможность Google. Знать статистику мало — важно делать правильные выводы.',
    ],
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find(a => a.slug === slug);
}
